module.exports = {
  thinkOfEngland: {
    jp: {
      asin: 'B08CK9CLQM',
      title: 'イングランドを想え',
      url: 'https://amzn.to/2D5Kq2W',
      author: 'KJ･チャールズ',
      unlimited: false,
    },
    en: {
      asin: 'B077J4Y2BZ',
      title: 'Think of England',
      url: 'https://amzn.to/2By9uQ0',
      author: 'KJ Charles',
      unlimited: false,
    },
  },
  diversion: {
    jp: {
      asin: 'B01LZ2CASG',
      title: '還流 (ドラッグ･チェイス #1)',
      url: 'https://amzn.to/2Dq3WY6',
      author: 'エデン･ウィンターズ',
      unlimited: true,
    },
    en: {
      asin: 'B00LIC5J00',
      title: 'Diversion (Diversion #1)',
      url: 'https://amzn.to/33hyh6a',
      author: 'Eden Winters',
      unlimited: false,
    },
  },
  mermaidMurders: {
    jp: {
      asin: 'B07L8WN6FL',
      title: 'マーメイド･マーダーズ (殺しのアート #1)',
      url: 'https://amzn.to/30Jnz5z',
      author: 'ジョシュ･ラニヨン',
      unlimited: false,
    },
    en: {
      asin: 'B018UJ80EA',
      title: 'The Mermaid Murders (The Art of Murder #1)',
      url: 'https://amzn.to/3jCzevF',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  monetMurders: {
    jp: {
      asin: 'B082H6P92M',
      title: 'モネ･マーダーズ (殺しのアート #2)',
      url: 'https://amzn.to/39NkkOA',
      author: 'ジョシュ･ラニヨン',
      unlimited: false,
    },
    en: {
      asin: 'B01MYC6ZOZ',
      title: 'The Monet Murders (The Art of Murder #2)',
      url: 'https://amzn.to/318TFb1',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  fairChance: {
    jp: {
      asin: 'B083NX8Q66',
      title: "フェア･チャンス (All's Fair #3)",
      url: 'https://amzn.to/3fZ7iQk',
      author: 'ジョシュ･ラニヨン',
      unlimited: false,
    },
    en: {
      asin: 'B01MSLD8L2',
      title: "Fair Chance (All's Fair #3)",
      url: 'https://amzn.to/3eXoTXz',
      author: 'Josh Lanyon',
      unlimited: false,
    },
  },
  dangerousThing: {
    jp: {
      asin: 'B00KW25SP8',
      title: '死者の囁き (アドリアン･イングリッシュ #2)',
      url: 'https://amzn.to/2EhDsZw',
      author: 'ジョシュ･ラニヨン',
      unlimited: true,
    },
    en: {
      asin: 'B0081C8RU4',
      title: 'A Dangerous Thing (The Adrien English Mysteries #2)',
      url: 'https://amzn.to/3fZxlH5',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  hellYouSay: {
    jp: {
      asin: 'B00N8RVP24',
      title: '悪魔の聖餐 (アドリアン･イングリッシュ #3)',
      url: 'https://amzn.to/33yQJHs',
      author: 'ジョシュ･ラニヨン',
      unlimited: true,
    },
    en: {
      asin: 'B006LNC468',
      title: 'The Hell You Say (The Adrien English Mysteries #3)',
      url: 'https://amzn.to/31jaLmO',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  deathOfAPirateKing: {
    jp: {
      asin: 'B00U6WBU2E',
      title: '海賊王の死 (アドリアン･イングリッシュ #4)',
      url: 'https://amzn.to/30jfc1F',
      author: 'ジョシュ･ラニヨン',
      unlimited: true,
    },
    en: {
      asin: 'B0067QUX9E',
      title: 'Death of a Pirate King (The Adrien English Mysteries #4)',
      url: 'https://amzn.to/2EB40VA',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  darkTide: {
    jp: {
      asin: 'B01BL25AEG',
      title: '瞑き流れ (アドリアン･イングリッシュ #5)',
      url: 'https://amzn.to/2Y4lP6A',
      author: 'ジョシュ･ラニヨン',
      unlimited: true,
    },
    en: {
      asin: 'B006N9XHLQ',
      title: 'The Dark Tide (The Adrien English Mysteries #5)',
      url: 'https://amzn.to/2CADLOA',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  soThisIsChristmas: {
    jp: {
      asin: 'B077ZGFZ7S',
      title: 'So This is Christmas (アドリアン･イングリッシュ #6)',
      url: 'https://amzn.to/3113J5T',
      author: 'ジョシュ･ラニヨン',
      unlimited: false,
    },
    en: {
      asin: 'B01N9AERR2',
      title: 'So This is Christmas (The Adrien English Mysteries #6)',
      url: 'https://amzn.to/2D8VL2M',
      author: 'Josh Lanyon',
      unlimited: true,
    },
  },
  dontLookBack: {
    jp: {
      asin: 'B00HD59DYY',
      title: 'ドント･ルックバック',
      url: 'https://amzn.to/31gcSaS',
      author: 'ジョシュ･ラニヨン',
      unlimited: true,
    },
    en: {
      asin: 'B00891DC8Y',
      title: "Don't Look Back",
      url: 'https://amzn.to/3gpPq1d',
      author: 'Josh Lanyon',
      unlimited: false,
    },
  },
  speechless: {
    jp: {
      asin: 'B01BL25AC8',
      title: 'Speechless',
      url: 'https://amzn.to/3a8sYat',
      author: 'キム･フィールディング',
      unlimited: false,
    },
    en: {
      asin: 'B008MMXCMQ',
      title: 'Speechless',
      url: 'https://amzn.to/3a3UDJV',
      author: 'Kim Fielding',
      unlimited: false,
    },
  },
  howToHowlAtTheMoon: {
    jp: {
      asin: 'B07J67WTTM',
      title: '月への吠えかた教えます (月吠えシリーズ #1)',
      url: 'https://amzn.to/2Y0Fu7p',
      author: 'イーライ･イーストン',
      unlimited: false,
    },
    en: {
      asin: 'B00T12QQOW',
      title: 'How to Howl at the Moon (Howl at the Moon #1)',
      url: 'https://amzn.to/2Y3Z6az',
      author: 'Eli Easton',
      unlimited: true,
    },
  },
  howToWalkLikeAMan: {
    jp: {
      asin: 'B07YXLFLG9',
      title: 'ヒトの世界の歩きかた (月吠えシリーズ #2)',
      url: 'https://amzn.to/3av0dVJ',
      author: 'イーライ･イーストン',
      unlimited: false,
    },
    en: {
      asin: 'B0176KQPH8',
      title: 'How to Walk Like a Man (Howl at the Moon #2)',
      url: 'https://amzn.to/3g00Wzx',
      author: 'Eli Easton',
      unlimited: true,
    },
  },
}
