module.exports = {
  menstrualCup: '月経カップ',
  minimalism: 'ミニマリズム',
  review: '感想',
  tvShow: '海外ドラマ',
  netflix: 'Netflix',
  englishBook: '洋書',
  adrienEnglish: 'アドリアン･イングリッシュ',
  joshLanyon: 'ジョシュ･ラニヨン',
  sawaSakura: '紗久楽さわ',
  couple: 'カップル',
  allsFair: "All's Fair",
  ranmaruZariya: '座裏屋蘭丸',
  zakk: 'ZAKK',
  canis: 'CANISシリーズ',
  akiUeda: '上田アキ',
  relocate: '海外移住',
  theArtOfMurder: '殺しのアート',
  audioBook: 'オーディオブック',
}
